> ```sql
CREATE TABLE public.Abonents (
	Abonents_ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	Abonents_SubjectName CHARACTER VARYING,
	Abonents_SubjectCode INTEGER,
	Abonents_DistrictName CHARACTER VARYING,
	Abonents_DistrictCode INTEGER,
	Abonents_CityName CHARACTER VARYING,
	Abonents_CityCode INTEGER,
	Abonents_AreaName CHARACTER VARYING,
	Abonents_AreaCode INTEGER,
	Abonents_StreetName CHARACTER VARYING,
	Abonents_StreetCode INTEGER,
	Abonents_FlatName CHARACTER VARYING,
	Abonents_FlatCode INTEGER,
	Abonents_HouseName CHARACTER VARYING,
	Abonents_HouseCode INTEGER,
	Abonents_Surname CHARACTER VARYING,
	Abonents_Name CHARACTER VARYING,
	Abonents_Patronymic CHARACTER VARYING,
	Abonents_GPSCode CHARACTER VARYING,
	Abonents_Note CHARACTER VARYING,
	Abonents_INN CHARACTER VARYING,
	Abonents_AIISNumber CHARACTER VARYING,
	Abonents_MessageCount INTEGER,
	Abonents_StatusCode INTEGER,
	Abonents_HouseBuildingName CHARACTER VARYING,
	Abonents_HouseBuildingCode INTEGER
);

CREATE TABLE public.Components(
	Component_ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	Component_Name character varying NOT NULL,
	Component_SwType integer NOT NULL UNIQUE,
	Component_UpdFoldName character varying
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_components
    ON public.components USING btree
    (component_swtype ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE public.ComponentsFunctions(
	ComponentFunction_ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	ComponentFunction_Name character varying,
	ComponentFunction_ComponentID integer NOT NULL REFERENCES public.Components (Component_ID),
	ComponentFunction_FunctionCode integer,
	ComponentFunction_SWTypeCode integer,
	ComponentFunction_Controlled boolean,
	ComponentFunction_Membership integer,
	ComponentFunction_Sort integer
);


CREATE TABLE public.Groups(
	Groups_ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	Groups_Name character varying NOT NULL,
	Groups_Parent_ID integer REFERENCES public.Groups (Groups_ID),
	Groups_GuideGroupsTypes_Code integer REFERENCES public.GuideGroupsTypes (GuideGroupsTypes_Code),
	Groups_DataControlsUnbalanceOn BOOLEAN,
	Groups_DataControlsNormPQOn BOOLEAN,
	Groups_DataControlsParams character varying NULL,
	Groups_CollectionDepth character varying NULL,
	Groups_DataControlsUnbalancePercent double precision,
	Groups_DataControlsUnbalanceDateTime TIMESTAMP,
	Groups_SynchID integer,
	Groups_SynchParentID integer,
	Groups_ExportOn BOOLEAN,
	Groups_ExportCode character varying,
	Groups_ContractorCode integer
);

CREATE INDEX IF NOT EXISTS ix_groups_parentid
    ON public.groups USING btree
    (groups_parent_id ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE public.GuideHeatScheme(
	GuideHeatScheme_ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	GuideHeatScheme_Code integer NOT NULL,
	GuideHeatScheme_Name character varying NOT NULL,
	GuideHeatScheme_Picture character varying,
	GuideHeatScheme_VisibleInstantValues character varying 
);

CREATE TABLE public.GuideInstantValues(
	GuideInstantValues_ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	GuideInstantValues_Code integer NOT NULL unique,
	GuideInstantValues_TypeDescription character varying,
	GuideInstantValues_Name_x1 character varying,
	GuideInstantValues_Name_x1000 character varying,
	GuideInstantValues_Name_x1000000 character varying,
	GuideInstantValues_Scalability BOOLEAN,
	GuideInstantValues_GuideEnergyGroup_Code integer,
	GuideInstantValues_MeasUnit integer,
	GuideInstantValues_MeasUnitsMultiplier integer,
	GuideInstantValues_ShortTypeDescription character varying
);


CREATE TABLE public.UniversalGuideValues(
	UniversalGuideValues_ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	UniversalGuideValues_UniversalGuide_Code integer NOT NULL REFERENCES public.UniversalGuide (UniversalGuide_Code),
	UniversalGuideValues_Type integer NOT NULL,
	UniversalGuideValues_StringValue character varying,
	UniversalGuideValues_IntValue integer,
	UniversalGuideValues_FloatValue DOUBLE precision,
	UniversalGuideValues_BoolValue BOOLEAN,
	UniversalGuideValues_DateTime TIMESTAMP,
	UniversalGuideValues_Code integer NOT NULL UNIQUE
);

CREATE TABLE public.UsersRoles(
	UserRole_ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	UserRole_Name character varying NOT NULL,
	UserRole_Description  character varying NULL,
	UserRole_Avatar bytea,
	UserRole_System BOOLEAN NOT NULL 
);

CREATE TABLE public.Users(
	User_ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	User_Name character varying NOT NULL,
	User_Password character varying NOT NULL,
	User_RoleID INTEGER NOT NULL REFERENCES public.UsersRoles (UserRole_ID),
	User_FullName character varying,
	User_Post character varying,
	User_Desc character varying,
	User_Avatar bytea,
	User_NetAccess character varying,
	User_ObjAccess character varying,
	User_AbonentAccess character varying,
	User_System boolean NOT NULL
);

REATE TABLE public.DeviceInfo(
	DeviceInfo_ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	DeviceInfo_Devices_ID integer NOT NULL REFERENCES public.Devices (Devices_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	DeviceInfo_GuideDeviceInfo_Code integer NOT NULL REFERENCES public.GuideDeviceInfo (GuideDeviceInfo_Code) ON DELETE CASCADE ON UPDATE CASCADE,
	DeviceInfo_Value character varying,
	DeviceInfo_EditDate TIMESTAMP,
	DeviceInfo_ReadFromNet BOOLEAN NOT NULL default false
);

CREATE TABLE public.Accounts(
	Accounts_ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	Accounts_GuideAccountsTypes_Code integer REFERENCES public.GuideAccountsTypes (GuideAccountsTypes_Code) ON DELETE SET NULL,
	Accounts_Abonents_ID integer NOT NULL REFERENCES public.Abonents (Abonents_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	Accounts_Code character varying,
	Accounts_Note character varying,
	Accounts_BillingConfig_ID integer,
	Accounts_ElectricGroupEnabled boolean NOT NULL default false,
	Accounts_GasGroupEnabled boolean NOT NULL default false,
	Accounts_WaterGroupEnabled boolean NOT NULL default false,
	Accounts_HeatGroupEnabled boolean NOT NULL default false
);

CREATE TABLE public.AccountsDevices(
	AccountsDevices_ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	AccountsDevices_Accounts_ID integer NOT NULL REFERENCES public.Accounts (Accounts_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	AccountsDevices_Devices_ID integer NOT NULL REFERENCES public.Devices (Devices_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	AccountsDevices_Note character varying
);

CREATE TABLE public.DeviceFiles(
	DeviceFiles_ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	DeviceFiles_Devices_ID integer NOT NULL NOT NULL REFERENCES public.Devices (Devices_ID),
	DeviceFiles_Name character varying NOT NULL,
	DeviceFiles_Expansion character varying NOT NULL,
	DeviceFiles_Content bytea NOT NULL
);

.............

> ```